<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<title>Cryptography and Security  authors/titles recent submissions</title>
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" type="text/css" media="screen" href="/css/arXiv.css?v=20170424" />
<link rel="stylesheet" type="text/css" media="screen" href="/bibex/bibex.css?20181009">
<link rel="alternate" type="application/rss+xml" title="Cryptography and Security " href="http://arxiv.org/rss/cs.CR"/>
<script src="/js/mathjaxToggle.min.js" type="text/javascript"></script>

<!-- Piwik -->
<script type="text/javascript">
var _paq = _paq || [];
_paq.push(["setDomains", ["*.arxiv.org"]]);
_paq.push(['trackPageView']);
_paq.push(['enableLinkTracking']);
(function()
{ var u="//webanalytics.library.cornell.edu/"; _paq.push(['setTrackerUrl', u+'piwik.php']); _paq.push(['setSiteId', 538]); var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0]; g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s); }
)();
</script>
<!-- End Piwik Code -->


</head>
<body class="with-cu-identity">

<noscript><img src="//webanalytics.library.cornell.edu/piwik.php?idsite=538&rec=1" style="border:0;" alt="" /></noscript>

<div id="cu-identity">
<div id="cu-logo">
<a id="insignia-link" href="http://www.cornell.edu/"><img src="/icons/cu/cul_signature_unstyled.gif" alt="Cornell University" width="283" height="76" border="0" /></a>
<div id="unit-signature-links">
<a id="cornell-link" href="http://www.cornell.edu/">Cornell University</a>
<a id="unit-link" href="http://www.library.cornell.edu/">Library</a>
</div>
</div>
<div id="support-ack">
<a href="https://confluence.cornell.edu/x/ALlRF">We gratefully acknowledge support from<br />the Simons Foundation<br /> and member institutions</a>
</div>
</div>
<div id="header">
<h1><a href="/">arXiv.org</a> &gt; <a href="/list/cs/recent">cs</a> &gt; <a href="/list/cs.CR/recent">cs.CR</a></h1>
<div id="search">
<form id="search-arxiv" method="GET" action="/search">
                
<div class="wrapper-search-arxiv">
<input class="keyword-field" type="text" name="query" placeholder="Search or Article ID"/>

<div class="filter-field">
<select name="searchtype">
<option value="all">All fields</option>
<option value="title">Title</option>
<option value="author">Author(s)</option>
<option value="abstract">Abstract</option>
<option value="comments">Comments</option>
<option value="journal_ref">Journal reference</option>
<option value="acm_class">ACM classification</option>
<option value="msc_class">MSC classification</option>
<option value="report_num">Report number</option>
<option value="paper_id">arXiv identifier</option>
<option value="doi">DOI</option>
<option value="orcid">ORCID</option>
<option value="author_id">arXiv author ID</option>
<option value="help">Help pages</option>
<option value="full_text">Full text</option></select>
</div>
<input class="btn-search-arxiv" value="" type="submit">
<div class="links">(<a href="/help">Help</a> | <a href="/search/advanced">Advanced search</a>)</div>
</div>
<input type="hidden" name="source" value="header">
</form>
</div>
</div>
<div id="content">
<div id="dlpage">
<h1>Cryptography and Security </h1>
<h2>Authors and titles for recent submissions</h2>
<ul>
<li><a href="/list/cs.CR/pastweek?skip=0&amp;show=25">Mon, 29 Oct 2018</a></li>
<li><a href="#item5">Fri, 26 Oct 2018</a></li>
<li><a href="#item12">Thu, 25 Oct 2018</a></li>
<li><a href="#item21">Wed, 24 Oct 2018</a></li>
<li><a href="/list/cs.CR/pastweek?skip=25&amp;show=25">Tue, 23 Oct 2018</a></li>
</ul>
<small>[ total of 34 entries:  <b>1-25</b> | <a href="/list/cs.CR/pastweek?skip=25&amp;show=25">26-34</a>  ]</small><br />
<small>[ showing 25 entries per page:  <a href="/list/cs.CR/pastweek?skip=0&amp;show=10">fewer</a> |  <a href="/list/cs.CR/pastweek?skip=0&amp;show=50">more</a> |  <a href="/list/cs.CR/pastweek?show=34">all</a> ]</small><br />
<h3>Mon, 29 Oct 2018</h3>
<dl>
<dt><a name="item1">[1]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.11179" title="Abstract">arXiv:1810.11179</a> [<a href="/pdf/1810.11179" title="Download PDF">pdf</a>, <a href="/format/1810.11179" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Content Protection in Named Data Networking: Challenges and Potential  Solutions
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Yu%2C+Y">Yong Yu</a>, 
<a href="/search/cs?searchtype=author&query=Li%2C+Y">Yannan Li</a>, 
<a href="/search/cs?searchtype=author&query=Du%2C+X">Xiaojiang Du</a>, 
<a href="/search/cs?searchtype=author&query=Chen%2C+R">Ruonan Chen</a>, 
<a href="/search/cs?searchtype=author&query=Yang%2C+B">Bo Yang</a>
</div>
<div class="list-comments mathjax">
<span class="descriptor">Comments:</span> 6 pages, 5 figures
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Cryptography and Security (cs.CR)</span>

</div>
</div>
</dd>
<dt><a name="item2">[2]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.11175" title="Abstract">arXiv:1810.11175</a> [<a href="/pdf/1810.11175" title="Download PDF">pdf</a>, <a href="/format/1810.11175" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> LRCoin: Leakage-resilient Cryptocurrency Based on Bitcoin for Data  Trading in IoT
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Yu%2C+Y">Yong Yu</a>, 
<a href="/search/cs?searchtype=author&query=Ding%2C+Y">Yujie Ding</a>, 
<a href="/search/cs?searchtype=author&query=Zhao%2C+Y">Yanqi Zhao</a>, 
<a href="/search/cs?searchtype=author&query=Li%2C+Y">Yannan Li</a>, 
<a href="/search/cs?searchtype=author&query=Du%2C+X">Xiaojiang Du</a>, 
<a href="/search/cs?searchtype=author&query=Guizani%2C+M">Mohsen Guizani</a>
</div>
<div class="list-comments mathjax">
<span class="descriptor">Comments:</span> 9 pages, 3 figures, 1 table
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Cryptography and Security (cs.CR)</span>

</div>
</div>
</dd>
<dt><a name="item3">[3]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.11153" title="Abstract">arXiv:1810.11153</a> (cross-list from cs.IT) [<a href="/pdf/1810.11153" title="Download PDF">pdf</a>, <a href="/ps/1810.11153" title="Download PostScript">ps</a>, <a href="/format/1810.11153" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Development and Analysis of Deterministic Privacy-Preserving Policies  Using Non-Stochastic Information Theory
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Farokhi%2C+F">Farhad Farokhi</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Information Theory (cs.IT)</span>; Cryptography and Security (cs.CR); Systems and Control (cs.SY); Optimization and Control (math.OC)

</div>
</div>
</dd>
<dt><a name="item4">[4]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.11063" title="Abstract">arXiv:1810.11063</a> (cross-list from cs.HC) [<a href="/pdf/1810.11063" title="Download PDF">pdf</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Sorry: Ambient Tactical Deception Via Malware-Based Social Engineering
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Trowbridge%2C+A">Adam Trowbridge</a>, 
<a href="/search/cs?searchtype=author&query=Westbrook%2C+J">Jessica Westbrook</a>, 
<a href="/search/cs?searchtype=author&query=Sharevski%2C+F">Filipo Sharevski</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Human-Computer Interaction (cs.HC)</span>; Cryptography and Security (cs.CR)

</div>
</div>
</dd>
</dl>
<h3>Fri, 26 Oct 2018</h3>
<dl>
<dt><a name="item5">[5]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10750" title="Abstract">arXiv:1810.10750</a> [<a href="/pdf/1810.10750" title="Download PDF">pdf</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> An Efficient Encryption Scheme with Verifiable Outsourced Decryption in  Mobile Cloud Computing
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Li%2C+J">Jing Li</a>, 
<a href="/search/cs?searchtype=author&query=Guan%2C+Z">Zhitao Guan</a>, 
<a href="/search/cs?searchtype=author&query=Du%2C+X">Xiaojiang Du</a>, 
<a href="/search/cs?searchtype=author&query=Zhang%2C+Z">Zijian Zhang</a>, 
<a href="/search/cs?searchtype=author&query=Wu%2C+J">Jun Wu</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Cryptography and Security (cs.CR)</span>

</div>
</div>
</dd>
<dt><a name="item6">[6]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10748" title="Abstract">arXiv:1810.10748</a> [<a href="/pdf/1810.10748" title="Download PDF">pdf</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Towards Delay-Tolerant Flexible Data Access Control for Smart Grid with  Renewable Energy Resources
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Guan%2C+Z">Zhitao Guan</a>, 
<a href="/search/cs?searchtype=author&query=Li%2C+J">Jing Li</a>, 
<a href="/search/cs?searchtype=author&query=Zhu%2C+L">Liehuang Zhu</a>, 
<a href="/search/cs?searchtype=author&query=Zhang%2C+Z">Zijian Zhang</a>, 
<a href="/search/cs?searchtype=author&query=Du%2C+X">Xiaojiang Du</a>, 
<a href="/search/cs?searchtype=author&query=Guizani%2C+M">Mohsen Guizani</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Cryptography and Security (cs.CR)</span>

</div>
</div>
</dd>
<dt><a name="item7">[7]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10746" title="Abstract">arXiv:1810.10746</a> [<a href="/pdf/1810.10746" title="Download PDF">pdf</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Achieving Efficient and Secure Data Acquisition for Cloud-supported  Internet of Things in Smart Grid
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Guan%2C+Z">Zhitao Guan</a>, 
<a href="/search/cs?searchtype=author&query=Li%2C+J">Jing Li</a>, 
<a href="/search/cs?searchtype=author&query=Wu%2C+L">Longfei Wu</a>, 
<a href="/search/cs?searchtype=author&query=Zhang%2C+Y">Yue Zhang</a>, 
<a href="/search/cs?searchtype=author&query=Wu%2C+J">Jun Wu</a>, 
<a href="/search/cs?searchtype=author&query=Du%2C+X">Xiaojiang Du</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Cryptography and Security (cs.CR)</span>

</div>
</div>
</dd>
<dt><a name="item8">[8]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10649" title="Abstract">arXiv:1810.10649</a> [<a href="/pdf/1810.10649" title="Download PDF">pdf</a>, <a href="/format/1810.10649" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> On the Effectiveness of Type-based Control Flow Integrity
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Farkhani%2C+R+M">Reza Mirzazade Farkhani</a>, 
<a href="/search/cs?searchtype=author&query=Jafari%2C+S">Saman Jafari</a>, 
<a href="/search/cs?searchtype=author&query=Arshad%2C+S">Sajjad Arshad</a>, 
<a href="/search/cs?searchtype=author&query=Robertson%2C+W">William Robertson</a>, 
<a href="/search/cs?searchtype=author&query=Kirda%2C+E">Engin Kirda</a>, 
<a href="/search/cs?searchtype=author&query=Okhravi%2C+H">Hamed Okhravi</a>
</div>
<div class="list-comments mathjax">
<span class="descriptor">Comments:</span> Annual Computer Security Applications Conference (ACSAC) 2018
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Cryptography and Security (cs.CR)</span>

</div>
</div>
</dd>
<dt><a name="item9">[9]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10939" title="Abstract">arXiv:1810.10939</a> (cross-list from cs.LG) [<a href="/pdf/1810.10939" title="Download PDF">pdf</a>, <a href="/format/1810.10939" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Evading classifiers in discrete domains with provable optimality  guarantees
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Kulynych%2C+B">Bogdan Kulynych</a>, 
<a href="/search/cs?searchtype=author&query=Hayes%2C+J">Jamie Hayes</a>, 
<a href="/search/cs?searchtype=author&query=Samarin%2C+N">Nikita Samarin</a>, 
<a href="/search/cs?searchtype=author&query=Troncoso%2C+C">Carmela Troncoso</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Machine Learning (cs.LG)</span>; Cryptography and Security (cs.CR); Machine Learning (stat.ML)

</div>
</div>
</dd>
<dt><a name="item10">[10]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10731" title="Abstract">arXiv:1810.10731</a> (cross-list from cs.LG) [<a href="/pdf/1810.10731" title="Download PDF">pdf</a>, <a href="/ps/1810.10731" title="Download PostScript">ps</a>, <a href="/format/1810.10731" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Law and Adversarial Machine Learning
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Kumar%2C+R+S+S">Ram Shankar Siva Kumar</a>, 
<a href="/search/cs?searchtype=author&query=O%27Brien%2C+D+R">David R. O&#x27;Brien</a>, 
<a href="/search/cs?searchtype=author&query=Albert%2C+K">Kendra Albert</a>, 
<a href="/search/cs?searchtype=author&query=Vilojen%2C+S">Salome Vilojen</a>
</div>
<div class="list-comments mathjax">
<span class="descriptor">Comments:</span> Corrected typos, Added references. 4 pages, submitted to NIPS 2018 Workshop on Security in Machine Learning
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Machine Learning (cs.LG)</span>; Cryptography and Security (cs.CR); Computers and Society (cs.CY); Machine Learning (stat.ML)

</div>
</div>
</dd>
<dt><a name="item11">[11]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10635" title="Abstract">arXiv:1810.10635</a> (cross-list from cs.DS) [<a href="/pdf/1810.10635" title="Download PDF">pdf</a>, <a href="/ps/1810.10635" title="Download PostScript">ps</a>, <a href="/format/1810.10635" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Lower Bounds for Oblivious Data Structures
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Jacob%2C+R">Riko Jacob</a>, 
<a href="/search/cs?searchtype=author&query=Larsen%2C+K+G">Kasper Green Larsen</a>, 
<a href="/search/cs?searchtype=author&query=Nielsen%2C+J+B">Jesper Buus Nielsen</a>
</div>
<div class="list-comments mathjax">
<span class="descriptor">Comments:</span> To appear at SODA'19
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Data Structures and Algorithms (cs.DS)</span>; Cryptography and Security (cs.CR)

</div>
</div>
</dd>
</dl>
<h3>Thu, 25 Oct 2018</h3>
<dl>
<dt><a name="item12">[12]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10464" title="Abstract">arXiv:1810.10464</a> [<a href="/pdf/1810.10464" title="Download PDF">pdf</a>, <a href="/format/1810.10464" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Preserving Both Privacy and Utility in Network Trace Anonymization
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Mohammady%2C+M">Meisam Mohammady</a>, 
<a href="/search/cs?searchtype=author&query=Wang%2C+L">Lingyu Wang</a>, 
<a href="/search/cs?searchtype=author&query=Hong%2C+Y">Yuan Hong</a>, 
<a href="/search/cs?searchtype=author&query=Louafi%2C+H">Habib Louafi</a>, 
<a href="/search/cs?searchtype=author&query=Pourzandi%2C+M">Makan Pourzandi</a>, 
<a href="/search/cs?searchtype=author&query=Debbabi%2C+M">Mourad Debbabi</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Cryptography and Security (cs.CR)</span>

</div>
</div>
</dd>
<dt><a name="item13">[13]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10157" title="Abstract">arXiv:1810.10157</a> [<a href="/pdf/1810.10157" title="Download PDF">pdf</a>, <a href="/ps/1810.10157" title="Download PostScript">ps</a>, <a href="/format/1810.10157" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Wireless Side-Lobe Eavesdropping Attacks
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Zhu%2C+Y">Yanzi Zhu</a>, 
<a href="/search/cs?searchtype=author&query=Ju%2C+Y">Ying Ju</a>, 
<a href="/search/cs?searchtype=author&query=Wang%2C+B">Bolun Wang</a>, 
<a href="/search/cs?searchtype=author&query=Cryan%2C+J">Jenna Cryan</a>, 
<a href="/search/cs?searchtype=author&query=Zhao%2C+B+Y">Ben Y. Zhao</a>, 
<a href="/search/cs?searchtype=author&query=Zheng%2C+H">Haitao Zheng</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Cryptography and Security (cs.CR)</span>; Networking and Internet Architecture (cs.NI)

</div>
</div>
</dd>
<dt><a name="item14">[14]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10123" title="Abstract">arXiv:1810.10123</a> [<a href="/pdf/1810.10123" title="Download PDF">pdf</a>, <a href="/format/1810.10123" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> SATE: Robust and Private Allegation Escrows
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Arun%2C+V">Venkat Arun</a>, 
<a href="/search/cs?searchtype=author&query=Kate%2C+A">Aniket Kate</a>, 
<a href="/search/cs?searchtype=author&query=Garg%2C+D">Deepak Garg</a>, 
<a href="/search/cs?searchtype=author&query=Druschel%2C+P">Peter Druschel</a>, 
<a href="/search/cs?searchtype=author&query=Bhattacharjee%2C+B">Bobby Bhattacharjee</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Cryptography and Security (cs.CR)</span>

</div>
</div>
</dd>
<dt><a name="item15">[15]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10121" title="Abstract">arXiv:1810.10121</a> [<a href="/pdf/1810.10121" title="Download PDF">pdf</a>, <a href="/format/1810.10121" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> nGraph-HE: A Graph Compiler for Deep Learning on Homomorphically  Encrypted Data
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Boemer%2C+F">Fabian Boemer</a>, 
<a href="/search/cs?searchtype=author&query=Lao%2C+Y">Yixing Lao</a>, 
<a href="/search/cs?searchtype=author&query=Wierzynski%2C+C">Casimir Wierzynski</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Cryptography and Security (cs.CR)</span>

</div>
</div>
</dd>
<dt><a name="item16">[16]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10109" title="Abstract">arXiv:1810.10109</a> [<a href="/pdf/1810.10109" title="Download PDF">pdf</a>, <a href="/ps/1810.10109" title="Download PostScript">ps</a>, <a href="/format/1810.10109" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Adversarial WiFi Sensing
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Zhu%2C+Y">Yanzi Zhu</a>, 
<a href="/search/cs?searchtype=author&query=Xiao%2C+Z">Zhujun Xiao</a>, 
<a href="/search/cs?searchtype=author&query=Chen%2C+Y">Yuxin Chen</a>, 
<a href="/search/cs?searchtype=author&query=Li%2C+Z">Zhijing Li</a>, 
<a href="/search/cs?searchtype=author&query=Liu%2C+M">Max Liu</a>, 
<a href="/search/cs?searchtype=author&query=Zhao%2C+B+Y">Ben Y. Zhao</a>, 
<a href="/search/cs?searchtype=author&query=Zheng%2C+H">Haitao Zheng</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Cryptography and Security (cs.CR)</span>

</div>
</div>
</dd>
<dt><a name="item17">[17]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10436" title="Abstract">arXiv:1810.10436</a> (cross-list from quant-ph) [<a href="/pdf/1810.10436" title="Download PDF">pdf</a>, <a href="/format/1810.10436" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Entropy in Quantum Information Theory -- Communication and Cryptography
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/quant-ph?searchtype=author&query=Majenz%2C+C">Christian Majenz</a>
</div>
<div class="list-comments mathjax">
<span class="descriptor">Comments:</span> PhD Thesis, University of Copenhagen, 144 pages. The abstract is shortened to meet ArXiv requirements, please see the pdf for a more informative abstract. Contains results from <a href="/abs/1809.10751">1809.10751</a>, <a href="/abs/1610.04214">1610.04214</a> and <a href="/abs/1605.00514">1605.00514</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Quantum Physics (quant-ph)</span>; Cryptography and Security (cs.CR); Information Theory (cs.IT)

</div>
</div>
</dd>
<dt><a name="item18">[18]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10369" title="Abstract">arXiv:1810.10369</a> (cross-list from cs.LG) [<a href="/pdf/1810.10369" title="Download PDF">pdf</a>, <a href="/format/1810.10369" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> The Faults in Our Pi Stars: Security Issues and Open Challenges in Deep  Reinforcement Learning
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Behzadan%2C+V">Vahid Behzadan</a>, 
<a href="/search/cs?searchtype=author&query=Munir%2C+A">Arslan Munir</a>
</div>
<div class="list-comments mathjax">
<span class="descriptor">Comments:</span> arXiv admin note: text overlap with <a href="/abs/1807.06064">arXiv:1807.06064</a>, <a href="/abs/1712.03632">arXiv:1712.03632</a>, <a href="/abs/1803.02811">arXiv:1803.02811</a>, <a href="/abs/1710.00814">arXiv:1710.00814</a> by other authors
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Machine Learning (cs.LG)</span>; Cryptography and Security (cs.CR); Machine Learning (stat.ML)

</div>
</div>
</dd>
<dt><a name="item19">[19]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10156" title="Abstract">arXiv:1810.10156</a> (cross-list from cs.AI) [<a href="/pdf/1810.10156" title="Download PDF">pdf</a>, <a href="/format/1810.10156" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Automatic Identification of Indicators of Compromise using Neural-Based  Sequence Labelling
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Zhou%2C+S">Shengping Zhou</a>, 
<a href="/search/cs?searchtype=author&query=Long%2C+Z">Zi Long</a>, 
<a href="/search/cs?searchtype=author&query=Tan%2C+L">Lianzhi Tan</a>, 
<a href="/search/cs?searchtype=author&query=Guo%2C+H">Hao Guo</a>
</div>
<div class="list-comments mathjax">
<span class="descriptor">Comments:</span> accepted by PACLIC 2018
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Artificial Intelligence (cs.AI)</span>; Cryptography and Security (cs.CR)

</div>
</div>
</dd>
<dt><a name="item20">[20]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.10031" title="Abstract">arXiv:1810.10031</a> (cross-list from cs.LG) [<a href="/pdf/1810.10031" title="Download PDF">pdf</a>, <a href="/format/1810.10031" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Stochastic Substitute Training: A Gray-box Approach to Craft Adversarial  Examples Against Gradient Obfuscation Defenses
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Hashemi%2C+M">Mohammad Hashemi</a>, 
<a href="/search/cs?searchtype=author&query=Cusack%2C+G">Greg Cusack</a>, 
<a href="/search/cs?searchtype=author&query=Keller%2C+E">Eric Keller</a>
</div>
<div class="list-comments mathjax">
<span class="descriptor">Comments:</span> Accepted by AISec '18: 11th ACM Workshop on Artificial Intelligence and Security. Source code at <a href="https://github.com/S-Mohammad-Hashemi/SST">this https URL</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Machine Learning (cs.LG)</span>; Artificial Intelligence (cs.AI); Cryptography and Security (cs.CR); Machine Learning (stat.ML)

</div>
</div>
</dd>
</dl>
<h3>Wed, 24 Oct 2018</h3>
<dl>
<dt><a name="item21">[21]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.09752" title="Abstract">arXiv:1810.09752</a> [<a href="/pdf/1810.09752" title="Download PDF">pdf</a>, <a href="/format/1810.09752" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Building an Emulation Environment for Cyber Security Analyses of Complex  Networked Systems
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Tanasache%2C+F+D">Florin Dragos Tanasache</a>, 
<a href="/search/cs?searchtype=author&query=Sorella%2C+M">Mara Sorella</a>, 
<a href="/search/cs?searchtype=author&query=Bonomi%2C+S">Silvia Bonomi</a>, 
<a href="/search/cs?searchtype=author&query=Rapone%2C+R">Raniero Rapone</a>, 
<a href="/search/cs?searchtype=author&query=Meacci%2C+D">Davide Meacci</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Cryptography and Security (cs.CR)</span>; Networking and Internet Architecture (cs.NI)

</div>
</div>
</dd>
<dt><a name="item22">[22]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.09551" title="Abstract">arXiv:1810.09551</a> [<a href="/pdf/1810.09551" title="Download PDF">pdf</a>, <a href="/format/1810.09551" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> IoTSan: Fortifying the Safety of IoT Systems
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Nguyen%2C+D+T">Dang Tu Nguyen</a>, 
<a href="/search/cs?searchtype=author&query=Song%2C+C">Chengyu Song</a>, 
<a href="/search/cs?searchtype=author&query=Qian%2C+Z">Zhiyun Qian</a>, 
<a href="/search/cs?searchtype=author&query=Krishnamurthy%2C+S+V">Srikanth V. Krishnamurthy</a>, 
<a href="/search/cs?searchtype=author&query=Colbert%2C+E+J+M">Edward J. M. Colbert</a>, 
<a href="/search/cs?searchtype=author&query=McDaniel%2C+P">Patrick McDaniel</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Cryptography and Security (cs.CR)</span>

</div>
</div>
</dd>
<dt><a name="item23">[23]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.09650" title="Abstract">arXiv:1810.09650</a> (cross-list from cs.LG) [<a href="/pdf/1810.09650" title="Download PDF">pdf</a>, <a href="/format/1810.09650" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> One Bit Matters: Understanding Adversarial Examples as the Abuse of  Redundancy
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Wang%2C+J">Jingkang Wang</a>, 
<a href="/search/cs?searchtype=author&query=Jia%2C+R">Ruoxi Jia</a>, 
<a href="/search/cs?searchtype=author&query=Friedland%2C+G">Gerald Friedland</a>, 
<a href="/search/cs?searchtype=author&query=Li%2C+B">Bo Li</a>, 
<a href="/search/cs?searchtype=author&query=Spanos%2C+C">Costas Spanos</a>
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Machine Learning (cs.LG)</span>; Cryptography and Security (cs.CR); Computer Vision and Pattern Recognition (cs.CV); Information Theory (cs.IT); Machine Learning (stat.ML)

</div>
</div>
</dd>
<dt><a name="item24">[24]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.09619" title="Abstract">arXiv:1810.09619</a> (cross-list from cs.LG) [<a href="/pdf/1810.09619" title="Download PDF">pdf</a>, <a href="/format/1810.09619" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Sparse DNNs with Improved Adversarial Robustness
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Guo%2C+Y">Yiwen Guo</a>, 
<a href="/search/cs?searchtype=author&query=Zhang%2C+C">Chao Zhang</a>, 
<a href="/search/cs?searchtype=author&query=Zhang%2C+C">Changshui Zhang</a>, 
<a href="/search/cs?searchtype=author&query=Chen%2C+Y">Yurong Chen</a>
</div>
<div class="list-comments mathjax">
<span class="descriptor">Comments:</span> To appear in NIPS2018
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Machine Learning (cs.LG)</span>; Cryptography and Security (cs.CR); Computer Vision and Pattern Recognition (cs.CV); Neural and Evolutionary Computing (cs.NE); Machine Learning (stat.ML)

</div>
</div>
</dd>
<dt><a name="item25">[25]</a>&nbsp;  <span class="list-identifier"><a href="/abs/1810.09438" title="Abstract">arXiv:1810.09438</a> (cross-list from cs.DC) [<a href="/pdf/1810.09438" title="Download PDF">pdf</a>, <a href="/format/1810.09438" title="Other formats">other</a>]</span></dt>
<dd>
<div class="meta">
<div class="list-title mathjax">
<span class="descriptor">Title:</span> Triad-NVM: Persistent-Security for Integrity-Protected and Encrypted  Non-Volatile Memories (NVMs)
</div>
<div class="list-authors">
<span class="descriptor">Authors:</span> 
<a href="/search/cs?searchtype=author&query=Awad%2C+A">Amro Awad</a>, 
<a href="/search/cs?searchtype=author&query=Njilla%2C+L">Laurent Njilla</a>, 
<a href="/search/cs?searchtype=author&query=Ye%2C+M">Mao Ye</a>
</div>
<div class="list-comments mathjax">
<span class="descriptor">Comments:</span> This paper is currently under submission. We arXiv our paper to establish credit for inventing this work
</div>
<div class="list-subjects">
<span class="descriptor">Subjects:</span> <span class="primary-subject">Distributed, Parallel, and Cluster Computing (cs.DC)</span>; Cryptography and Security (cs.CR)

</div>
</div>
</dd>
</dl>
<ul>
<li><a href="/list/cs.CR/pastweek?skip=0&amp;show=25">Mon, 29 Oct 2018</a></li>
<li><a href="#item5">Fri, 26 Oct 2018</a></li>
<li><a href="#item12">Thu, 25 Oct 2018</a></li>
<li><a href="#item21">Wed, 24 Oct 2018</a></li>
<li><a href="/list/cs.CR/pastweek?skip=25&amp;show=25">Tue, 23 Oct 2018</a></li>
</ul>
<small>[ total of 34 entries:  <b>1-25</b> | <a href="/list/cs.CR/pastweek?skip=25&amp;show=25">26-34</a>  ]</small><br />
<small>[ showing 25 entries per page:  <a href="/list/cs.CR/pastweek?skip=0&amp;show=10">fewer</a> |  <a href="/list/cs.CR/pastweek?skip=0&amp;show=50">more</a> |  <a href="/list/cs.CR/pastweek?show=34">all</a> ]</small><br />
</div>
<br/><small><a id="mathjax_toggle" href="javascript:setMathjaxCookie()">Disable MathJax</a> (<a href="/help/mathjax/">What is MathJax?</a>)</small><script type="text/javascript" language="javascript">mathjaxToggle();</script>
</div>
<div id="footer">
<div class="footer-text">

<hr />
<p>Links to:
<a href="/" accesskey="a">arXiv</a>, 
<a href="/form/cs">form interface</a>,
<a href="/find/cs">find</a>,
<a href="/archive/cs">cs</a>, <a href="/list/cs/new">new</a>, <a href="/list/cs/1810">1810</a>,
<a href="/help/contact">contact</a>,
<a href="/help/" accesskey="h"><span class="accesskey">h</span>elp</a>&nbsp;
<small>(<a href="/help/accesskeys">Access key</a> information)</small>
</p>
<hr />
</div>
<div class="social"><a href="https://twitter.com/arxiv"><img src="//static.arxiv.org/icons/twitter_logo_blue.png" alt="Twitter" title="Follow arXiv on Twitter"></a></div>
</div>
</body>
</html>
